// Event types that are generated by the parser.
#pragma once

#include <cstdint>

namespace itch {

#pragma pack(push, 1)
// SYSTEM MESSAGES
struct SystemEvent {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  char event_code;
};

struct StockDirectory {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  char stock[8];
  char market_category;
  char financial_status_indicator;
  uint32_t round_lot_size;
  char round_lots_only;
  char issue_clarification;
  char issue_subtype[2];
  char authenticity;
  char short_sale_threshold_indicator;
  char ipo_flag;
  char luld_reference_price_tier;
  char etp_flag;
  uint32_t etp_leverage_factor;
  char inverse_indicator;
};

struct StockTradingAction {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  char stock[8];
  char trading_state;
  char reserved;
  char reason[4];
};

struct RegSHORestriction {
  char message_type;
  uint16_t locate_code;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  char stock[8];
  char reg_sho_action;
};

struct MarketParticipantPosition {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  char mpid[4];
  char stock[8];
  char primary_market_maker;
  char market_maker_mode;
  char market_participant_state;
};

struct MWCBDeclineLevelMessage {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  uint64_t level_1;
  uint64_t level_2;
  uint64_t level_3;
};

struct MWCBStatusMessage {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  char breached_level;
};

struct IPOQuotingPeriodUpdate {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  char stock[8];
  uint32_t ipo_quotation_release_time;
  char ipo_quotation_releas_qualifier;
  uint32_t ipo_price;
};

struct LULDAuctionCollar {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  char stock[8];
  uint32_t auction_collar_reference_price;
  uint32_t upper_auction_collar_price;
  uint32_t lower_auction_collar_price;
  uint32_t auction_collar_extension;
};

struct OperationalHalt {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  char stock[8];
  char market_code;
  char operational_halt_action;
};

// ORDER MESSAGES

struct AddOrder {
  char message_type;          // 1
  uint16_t stock_locate;      // 2
  uint16_t tracking_number;   // 2
  uint8_t timestamp[6];       // 6
  uint64_t order_ref_number;  // 8
  uint8_t buy_sell_indicator; // 1
  uint32_t shares;            // 4
  char stock[8];              // 8
  uint32_t price;             // 4
};

struct AddOrderWithMPID {
  char message_type;          // 1
  uint16_t stock_locate;      // 2
  uint16_t tracking_number;   // 2
  uint8_t timestamp[6];       // 6
  uint64_t order_ref_number;  // 8
  uint8_t buy_sell_indicator; // 1
  uint32_t shares;            // 4
  char stock[8];              // 8
  uint32_t price;             // 4
  char attribution[4];
};

struct ExecOrder {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  uint64_t order_ref_number;
  uint32_t executed_shares;
  uint64_t match_number;
};

struct ExecOrderWithMessage {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  uint64_t order_ref_number;
  uint32_t executed_shares;
  uint64_t match_number;
  char printable;
  uint32_t execution_price;
};

struct CancelOrder {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  uint64_t order_ref_number;
  uint32_t cancelled_shares;
};

struct DeleteOrder {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  uint64_t order_ref_number;
};

struct ReplaceOrder {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  uint64_t original_order_ref_number;
  uint64_t new_order_ref_number;
  uint32_t shares;
  uint32_t price;
};

// TRADE MESSAGES

struct TradeMessageNonCross {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  uint64_t order_ref_number;
  char buy_sell_indicator;
  uint32_t shares;
  char stock[8];
  uint32_t price;
  uint64_t match_number;
};

struct TradeMessageCross {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  uint64_t shares;
  char stock[8];
  uint32_t cross_price;
  uint64_t match_number;
  char cross_type;
};

struct BrokenTrade {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  uint64_t match_number;
};

// NET ORDER IMBALANCE buy_sell_indicator

struct NOIIMessage {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  uint64_t paired_shares;
  uint64_t imbalance_shares;
  char imbalance_direction;
  char stock[8];
  uint32_t far_price;
  uint32_t near_price;
  uint32_t current_reference_price;
  char cross_type;
  char price_variation_indicator;
};

// other stuff

struct DirectListingWithCapitalRaisePriceDiscoveryMessage {
  char message_type;
  uint16_t stock_locate;
  uint16_t tracking_number;
  uint8_t timestamp[6];
  char stock[8];
  char open_eligibility_status;
  uint32_t minimum_allowable_price;
  uint32_t maximum_allowable_price;
  uint32_t near_execution_price;
  uint32_t lower_price_range_collar;
  uint32_t upper_price_range_collar;
};

#pragma pack(pop)

} // namespace itch